### ISSUE TITLE
Duplicate items when dropping on nested list

### ISSUE THREAD

**Issue by categulario** [rniemeyer/knockout-sortable#111]
That's it, I have a nested set of sortables and I drag an item into some other as child it dupplicates (so I can see two identical items inside), or sometimes the item is inside and when I drag it out of its list it duplicates (leaving a copy inside the original container).

http://jsfiddle.net/Ln9e8/

In the example I reproduce the second case

**Comment by chrisjcalderon** [comment]
Had the same problem described on this thread and the $(el).remove();  code replacement worked for me...
