### ISSUE TITLE
AMD Support Bug with jQuery UI 1.11

### ISSUE THREAD

**Issue by khakulov** [rniemeyer/knockout-sortable#121]
Official Documentation of jQuery UI(http://learn.jquery.com/jquery-ui/environments/amd/) says that you should require jQuery UI modules like:
```
require([ "jquery-ui/sortable" ], function( sortable ) {
    ...
});
```

But in knockout-sortable (Line 5) is like:
```
define(["knockout", "jquery", "jquery.ui.sortable"], factory);
```

I think it must be like this
```
define(["knockout", "jquery", "jquery.ui/sortable"], factory);
```

**Comment by rniemeyer** [comment]
This has been changed in `0.10.0`

**Comment by ajssd** [comment]
Still does not seem right.  Instead of
`define(["knockout", "jquery", "jquery.ui/sortable"], factory);`

shouldn't it be this instead?
`define(["knockout", "jquery", "jquery-ui/sortable"], factory);`

It must be "jquery-ui" not "jquery.ui" otherwise require won't be able to find it.

**Comment by rniemeyer** [comment]
This has been fixed. It now uses `jquery-ui/sortable` and `jquery-ui/draggable`.
