### ISSUE TITLE
Consider /jQuery.UI.Interactions.Sortable for NuGet dependency

### ISSUE THREAD

**Issue by BellaCode** [rniemeyer/knockout-sortable#127]
I noticed that jQuery.UI has a NuGet package for just the sortable portion of the library.  Since your great KO extension is focused just on the sortable feature of jQueryUI, I wonder if this would be a lightweight alternative for a dependency, rather than jQuery.UI.Combined.

I'm not sure if you'd have to produce two NuGet packages to handle both cases (combined vs. just sortable).

**Comment by jamieide** [comment]
This would be very helpful. We're using Bootstrap and there is some overlap with jQuery UI so I don't want to include the full UI.Combined library. Also, many of the jQUery UI components look dated.

**Comment by rniemeyer** [comment]
The sortable Nuget package does not appear to be updated since 2011. I am going to stick with the combined package for now, but am happy to revisit it in the future.
