### ISSUE TITLE
Issues of duplicate entries in list

### ISSUE THREAD

**Issue by sgringwe** [rniemeyer/knockout-sortable#129]
When I drag elements on the latest version of the sortable i get duplicate records in the list - one that is the original and one that is the new item. This happens even if I completely change the array. Any ideas why? This behavior is changed from version 0.8.6

**Comment by bufobufo** [comment]
@sgringwe: Can it be that you've been using a template for the sortable-binding which contains a comment at root level? I had the same problem where moving that evil comment one level deeper inside the template fixed the issue. 
@rniemeyer: Maybe this little gotcha is worth a hint in the documentation. Thank you for knockout-sortable, by the way :)

http://jsfiddle.net/bufobufo/8b0e3rmp/

**Comment by anthonyvscode** [comment]
@bufobufo you are a legend, removing the comment at root level fixed the issue for me.

**Comment by bbarber** [comment]
Duplicate entries are being removed from the list:
http://jsfiddle.net/hw9B2/1602/

(drag the first element to the bottom 3 times, one will be removed)
