### ISSUE TITLE
When Sortable is in template, it is not working

### ISSUE THREAD

**Issue by martinpare** [rniemeyer/knockout-sortable#136]
I try to put a Sortable div within a template but it is not working. Please help.
jsFiddle (from the simple Tasks example): http://jsfiddle.net/martinpare/8wosujL8/

Thanks in advance.

**Comment by rniemeyer** [comment]
The comments / text nodes inside of your template are causing issues. If you try a newer version of the sortable plugin, then it should be resolved. Here is your fiddle with a newer verison: http://jsfiddle.net/rniemeyer/gmmgvk24/ .  Hope that helps!

**Comment by martinpare** [comment]
Thanks. You solved the problem.
