### ISSUE TITLE
passing options to sortable

### ISSUE THREAD

**Issue by kssulliv** [rniemeyer/knockout-sortable#137]
I need to pass an axis 'x' option in sortable and I have been unable to figure out how to get that working. Currently I have overridden the jqueryui sortable create method but I think from you documentation there might be a better way to pass it through the 'div' in the template (I have two sortable lists on my page - one horizontal and one vertical so I need this setting to just effect one list).

Thank you

**Comment by rniemeyer** [comment]
You can pass any options through to the sortable using the `options` key like:

`sortable: { data: items, options: { axis: 'x' } }`

Hope that helps!
