### ISSUE TITLE
Sortable with KO 3.3 Template Engine lodash

### ISSUE THREAD

**Issue by tugas** [rniemeyer/knockout-sortable#149]
Hello, great job on this plugin, i have ran into a issue with duplicated entries on drag-sorting. I'm using loadsh as my template engine and i think this is the problem here is an example that is similar of what i'm doing base on your examples [sample in fiddle](http://jsfiddle.net/Jr2rE/581/), when dragging between the boxes some times values become duplicated even within the same box.

Any ideias? Thanks

**Comment by tugas** [comment]
This is bad i know replying to my own question but i found out the problem.
`precompiled = _.template("{{ with($data) { }} " + templateSource.text() + " {{ } }}");`
should be used without spaces like this
 `precompiled = _.template("{{with($data){}}" + templateSource.text() + "{{}}}");`

I hope at least this helps others. 
Thanks.

**Comment by rniemeyer** [comment]
@tugas - thanks! will surely leave this in case others run into the problem.
