### ISSUE TITLE
Removing element after drop

### ISSUE THREAD

**Issue by akursikov** [rniemeyer/knockout-sortable#167]
In your fiddles ([this](http://jsfiddle.net/rniemeyer/hw9B2/), [this](http://jsfiddle.net/rniemeyer/Jr2rE/)) elements just removed after drop. It's issue for v0.14.

**Comment by rniemeyer** [comment]
@akursikov - there was an issue with it looking for `ko.options` which is only in Knockout 3.4+, so with any version older than that it was erroring out. This is fixed in `0.14.1`. Thanks for alerting me to this issue.
