### ISSUE TITLE
items in fiddle disappearing when dragged and dropped

### ISSUE THREAD

**Issue by cyrus86** [rniemeyer/knockout-sortable#168]
This didn't happen the last time I checked out the fiddles, but is seems like the items are being deleted after dragging and dropping them. e.g. in this fiddle http://jsfiddle.net/rniemeyer/AC49j/

**Comment by rniemeyer** [comment]
@cyrus86 - This is fixed in `0.14.1`. There was an issue in `0.14.0` when using versions of Knockout less than 3.4.0. Thanks!
