### ISSUE TITLE
Request: buttons only version (without drag)

### ISSUE THREAD

**Issue by trinzia** [rniemeyer/knockout-sortable#170]
Hi, 

I would like to request a version (or Fiddle), in which up/down buttons may be used to sort the list, instead of dragging.  This is useful in the case where the dragged item is too large a percentage of the screen-height (such as rearranging pages) to be able to comfortably rearrange.

Also (maybe doesn't go in this topic, but ...), is there a way to "add item after"?  In all the Task List examples, the item is added at the end.  If I placed a button inside a list-item, could I use it to add an item immediately after that list item?

Thanks so much.

**Comment by rniemeyer** [comment]
@trinzia - Here is a sample with three buttons for inserting a task, moving up, and moving down. Please let me know if you have any questions about the sample: http://jsfiddle.net/rniemeyer/aj1fq6sr/ . Thanks!

**Comment by trinzia** [comment]
Thanks so much, this sample will help me learn. :)
