### ISSUE TITLE
change to require needed for jQuery-ui 1.12

### ISSUE THREAD

**Issue by ajssd** [rniemeyer/knockout-sortable#175]
In jQuery-ui 1.12, released July 8, 2016, there was a change in directory structure, with a number of files moving into a 'widgets' subdirectory.  It's described here:

[https://jqueryui.com/upgrade-guide/1.12/#moved-widgets-and-effects-source-files-into-folders](https://jqueryui.com/upgrade-guide/1.12/#moved-widgets-and-effects-source-files-into-folders)

This means that requiring in 'jquery-ui/sortable' and 'jquery-ui/draggable' no longer works.  You have to require in jquery-ui/widgets/sortable and jquery-ui/widgets/draggable.  

In the interim, we can add a map to our requirejs.config, like this:

```
    map: {
        '*': {
            'jquery-ui/draggable': 'jquery-ui/widgets/draggable',
            'jquery-ui/sortable': 'jquery-ui/widgets/sortable'
        }
    }

```

but that is a stopgap, since it means touching every one of our requirejs.config files.

Can you please update knockout-sortable to be more compatible with jQuery 1.12?

**Comment by rniemeyer** [comment]
This one has been addressed and a new version released (1.0.0). Thanks!
