### ISSUE TITLE
contenteditable within sortable not working

### ISSUE THREAD

**Issue by Jeff-14159** [rniemeyer/knockout-sortable#178]
If there is a contenteditable="true" nested somewhere within a sortable loop that content editable is broken...  

not sure but if you are checking the nodeType to see if we can click and move it can we first verify if it has the attribute contenteditable="true" then can we treat it like an input element???

IE 11 with knockout-sortable@0.14.1

Thanks,
Jeff

**Comment by Jeff-14159** [comment]
please remove this issue... found to be issue with jqueryUI sortable.... need to add:

ko.bindingHandlers.sortable.options.cancel = '.wysiwyg-editor'

Thanks,
Jeff

**Comment by rniemeyer** [comment]
@Jeff-14159 - sounds good - glad that you found your issue.
