### ISSUE TITLE
sortable dissapears after first drop

### ISSUE THREAD

**Issue by clearbucketLabs** [rniemeyer/knockout-sortable#190]
I see the example works fine, and i've swapped to using the same libraries but for some reason when i apply to my use case using bootstrap 3, after it's dragged once even if not dropped the top style coordinates start using the top of the window or screen meaning it goes from say top -100px or so to -2300px after it's dragged then stays that way until a page reload.  i've tried adjusting parents to relative but still no go.

**Comment by rniemeyer** [comment]
@clearbucketLabs - do you have a way to create some type of reproduction that I could run?

**Comment by clearbucketLabs** [comment]
Seems like if window is scrolled down a bit, even a few px the offset is off, if scrolled right to the top it's perfect.  it could be something else messing something up so i'll check and post an update first before wasting time.

**Comment by clearbucketLabs** [comment]
So it seems it's body { overflow-x: hidden;}   that messed it up.  Why its there i forget, there was a good reason at least but why it messes it up i don't know.

**Comment by rniemeyer** [comment]
@clearbucketLabs - glad that you got it sorted out.
