### ISSUE TITLE
Sortable not working with latest jquery

### ISSUE THREAD

**Issue by PilotC150** [rniemeyer/knockout-sortable#192]
I recently discovered that a table that I have sorting with this library has broken since upgrading to the latest version of jQuery (3.2.0).  I tried updating to latest of jQuery UI (1.12.1) and latest knockoutjs (3.4.2) and it's still not working.

I'm able to drag a row but nothing visually rearranges while I'm dragging and the dropping fails.

Are there any other components that I'm missing that would need to be updated?  Is this a known issue?

**Comment by rniemeyer** [comment]
@PilotC150 - here is a sample in jsFiddle with all of the latest: https://jsfiddle.net/rniemeyer/ugk4m0zv/

Maybe you can try to create something to reproduce your issue?

Thanks!

**Comment by PilotC150** [comment]
Thanks so much for the quick feedback and the jsFiddle.  Turns out I wasn't on latest jQuery.  I was using 3.2.0, not 3.2.1.

Once upgrading to 3.2.1 it started working again.

**Comment by rniemeyer** [comment]
@PilotC150 - great to hear. Glad it is working for you again!
