### ISSUE TITLE
Sortable not working after upgrading to knockout 3.5

### ISSUE THREAD

**Issue by sanderevers84** [rniemeyer/knockout-sortable#198]
After upgrading to KnockoutJS version 3.5.0, the sortable plugin stopped working.

![koproblem](https://user-images.githubusercontent.com/21587499/54991857-208cf500-4fbe-11e9-907c-caf4fa95a38f.png)

After adding an element to the array the element appears twice, 
when removing the element both elemenst are removed. 
Readding the same element and it will show three elements. 
This increases every time by one.

The shown JS error is thrown after removing one of the elements.

**Comment by JasperTey** [comment]
I also just noticed this, and had to downgrade to Knockout 3.4.2 in the meantime. Subscribing for notifications on the progress of this issue.

**Comment by rniemeyer** [comment]
@sanderevers84 @JasperTey - I am taking a look at this issue. Just to ensure that I am reproducing the same issue, can either of you verify taht with `3.5.0`, it works fine if you use binding syntax like `sortable: { data: tasks }` rather than `sortable: tasks`.

**Comment by rniemeyer** [comment]
I have a branch with a fix that you can try: https://github.com/rniemeyer/knockout-sortable/blob/defect-with-ko-3-5-0/build/knockout-sortable.min.js.  I want to do some additional testing before moving into master and would love to hear that it does solve your issues.

**Comment by sanderevers84** [comment]
@rniemeyer Both using the `sortable: { data: task }` syntax and your fix solved my issue. Thanks.

**Comment by JasperTey** [comment]
> use binding syntax like `sortable: { data: tasks }` rather than `sortable: tasks`.

Yup, confirmed working on my end too after switching to this syntax.

**Comment by dove** [comment]
I can confirm that sortable is working for me after upgrading to 3.5 (I already had `{sortable: {data: task}` binding

**Comment by JasperTey** [comment]
What's the status on moving the fix into master?

**Comment by rniemeyer** [comment]
Version 1.2.0 is out now with compatibility fixes for KO 3.5.0 and 3.5.1. Thanks. Sorry for the delay. I have no excuse :)

**Comment by SZaraqKhanA** [comment]
I am still facing the following issues after re doing all the steps mentioned above:

- After adding an element to the array the element appears twice,
- when removing the element both elemenst are removed.
- Readding the same element and it will show three elements.
- This increases every time by one.

**Comment by rniemeyer** [comment]
@SZaraqKhanA - do you have a some kind of sample that I might be able to look at?
