### ISSUE TITLE
Get an error after clean data

### ISSUE THREAD

**Issue by dxvladislavvolkov** [rniemeyer/knockout-sortable#206]
I have a simple example where I try to clean data of elements but after it, I get an error
Error: cannot call methods on draggable prior to initialization; attempted to call method 'destroy'

So, I researched your source code and found that you are trying to destroy component without any conditions and checkshttps://github.com/rniemeyer/knockout-sortable/blob/master/src/knockout-sortable.js#L430

and I think you need to add something like this:
https://github.com/rniemeyer/knockout-sortable/blob/master/src/knockout-sortable.js#L366

To reproduce:
1. Download the attached example
2. Run it
3. Click on the button
[knockout.zip](https://github.com/rniemeyer/knockout-sortable/files/6584242/knockout.zip)

**Comment by rniemeyer** [comment]
@dxvladislavvolkov - your suggested change, looks like a good fix

**Comment by rniemeyer** [comment]
@dxvladislavvolkov - ok - this is fixed in v1.2.1. Thanks!

**Comment by dxvladislavvolkov** [comment]
@rniemeyer thank you!
